#!/bin/sh

# This file is managed by Puppet. Changes will be overwritten during the next maintenance cycle.

IPADDR=`ifconfig eth0 | grep addr`

cat /etc/system-release > /etc/issue
cat << _EOF_ >> /etc/issue

$IPADDR.

_EOF_
